// Injection tokens for dependency injection
export const JOB_REPOSITORY = 'JOB_REPOSITORY';
export const BUILDING_SURVEY_REPOSITORY = 'BUILDING_SURVEY_REPOSITORY';
export const BUILDING_AGGREGATE_REPOSITORY = 'BUILDING_AGGREGATE_REPOSITORY';
export const PARSER_SERVICE = 'PARSER_SERVICE';
export const BUILDING_AGGREGATE_SERVICE = 'BUILDING_AGGREGATE_SERVICE';
